evaluation:
  no_cuda: True # Set it True if you don't need cuda in eval stage
  cuda_device: 0 # Specify the index if you use cuda and have multiple cuda devices
  method_list: [C-FID,t-SNE,Distribution]
  iter_disc: 2000
  iter_pred: 5000
  rnn_name: 'lstm'
  seq_len: 1
  non_ts_cols: []